search/urls.py
from django.conf.urls import url

from . import views

app_name = 'search'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^querybuilder/$', views.querybuilder, name='querybuilder'),
    url(r'^querybuilder/(?P<menuid>[-\w]+)/all_json_models/$', views.all_json_models, name='all_json_models'),
    url(r'^querybuilder/(?P<menuid>[-\w]+)/(?P<menuval>[-\w]+)/all_search_options/$', views.all_search_options, name='all_search_options'),
    url(r'^querybuilder/(?P<page>\d+)/(?P<results_per_page>\d+)/*$', views.querypage, name='querypage'),
    url(r'^querybuilder/export/*$', views.query_export, name='exportcsv'),
    url(r'^phenotypes/$', views.showPhenotypes, name='showPhenotypes'),
    url(r'^phenotypes/(?P<phenotype_id>\w+)/data/$', views.getPhenotypePlotData, name='getPhenotypePlotData'),
    url(r'^phenotypes/(?P<phenotype_id>\w+)/$', views.showPhenotypePlot, name='showPhenotypePlot'),
    url(r'^platforms/$', views.showPlatforms, name='showPlatforms'),
    url(r'^studies/$', views.showStudies, name='showStudies'),
    url(r'^qcs/$', views.showQCs, name='showQCs'),
    url(r'^sources/$', views.showSources, name='showSources'),
    url(r'^collections/$', views.showCollections, name='showCollections'),
    url(r'^missing/$', views.showMissing, name='showMissing'),
    url(r'^missing/(?P<study_id>\w+)/$', views.showMissingStudy, name='showMissingStudy'),
    url(r'^individuals/$', views.showIndividuals, name='showIndividuals'),
    url(r'^individuals/data$', views.getIndividualData, name='getIndividualData'),
    url(r'^samples/$', views.showSamples, name='showSamples'),
    url(r'^samples/data$', views.getSampleData, name='getSampleData'),
    url(r'^duplicateSampleIDs/$', views.duplicateSampleIDs, name='duplicateSampleIDs'),
    url(r'^API/query/$', views.APIQuery, name='APIQuery'),
    # url(r'^conflictingSampleIDs/$', views.conflictingSampleIDs, name='conflictingSampleIDs'),
]

search/views.py
# external imports
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import csv
import json
import io
import time
from collections import defaultdict, OrderedDict
import pprint
from django.views.decorators.csrf import csrf_exempt
from .duplicates import get_duplicate_sampleIDs
from django.contrib.auth import authenticate
import re

# internal imports
from .models import IndividualIdentifier, BinaryPhenotypeValue, QualitativePhenotypeValue, QuantitiatvePhenotypeValue, Phenotype, Platform, Individual, Study, Sample, Source, QC, Collection, StudySample, PhenodbIdentifier, MissingSampleID
from .tables import PhenotypeTable, PlatformTable, StudyTable, QCTable, SourceTable, CollectionTable, MissingTable, MissingStudyTable, ConflictingSampleIDsTable

def home(request):
    return render(request, 'search/home.html', {})

def showPlatforms(request):
    table = PlatformTable(Platform.objects.all())
    return render(request, 'search/dataview.html', {'table': table})

def showStudies(request):
    table = StudyTable(Study.objects.all())
    return render(request, 'search/dataview.html', {'table': table})

def showQCs(request):
    table = QCTable(QC.objects.all())
    return render(request, 'search/dataview.html', {'table': table})

def showSources(request):
    table = SourceTable(Source.objects.all())
    return render(request, 'search/dataview.html', {'table': table})

def showCollections(request):
    table = CollectionTable(Collection.objects.all())
    return render(request, 'search/dataview.html', {'table': table})

def showMissing(request):
    study_counts = []
    for study in Study.objects.all():
        study_counts.append({'study_id': study.id, 'study_name': study.study_name, 'missing_sample_count': MissingSampleID.objects.filter(study_id=study.id).count()})

    table = MissingTable(study_counts)
    return render(request, 'search/dataview.html', {'table': table})

def showMissingStudy(request, study_id):
    table = MissingStudyTable(MissingSampleID.objects.filter(study_id=study_id))
    return render(request, 'search/dataview.html', {'table': table})

def showPhenotypes(request):
    phenotypes = Phenotype.objects.all()
    phenotype_values = []
    for phenotype in phenotypes:
        values_str = ""
        if phenotype.phenotype_type.phenotype_type == 'binary':
            values_dict_array = BinaryPhenotypeValue.objects.filter(phenotype_id=phenotype.id).order_by('phenotype_value').values('phenotype_value').distinct()
            values_list = []
            for value_dict in values_dict_array:
                values_list.append(str(value_dict['phenotype_value']))
            values_str = ", ".join(values_list)
            not_null_total = BinaryPhenotypeValue.objects.filter(phenotype_id=phenotype.id, phenotype_value__isnull=False).values('phenotype_value').count()
        elif phenotype.phenotype_type.phenotype_type == 'qualitative':
            values_dict_array = QualitativePhenotypeValue.objects.filter(phenotype_id=phenotype.id).values('phenotype_value').distinct()
            values_list = []
            for value_dict in values_dict_array:
                values_list.append(str(value_dict['phenotype_value']))
            values_str = ", ".join(values_list)
            not_null_total = QualitativePhenotypeValue.objects.filter(phenotype_id=phenotype.id, phenotype_value__isnull=False).values('phenotype_value').count()
        elif phenotype.phenotype_type.phenotype_type == 'quantitative':
            values_dict_array = QuantitiatvePhenotypeValue.objects.filter(phenotype_id=phenotype.id).order_by('phenotype_value').values('phenotype_value').distinct()
            values_list = []
            for value_dict in values_dict_array:
                values_list.append(value_dict['phenotype_value'])
            if len(values_list) > 0:
                values_str = "...".join((str(min(values_list)), str(max(values_list))))
            else:
                values_list = ""
            not_null_total = QuantitiatvePhenotypeValue.objects.filter(phenotype_id=phenotype.id, phenotype_value__isnull=False).values('phenotype_value').count()
        phenotype_values.append({'phenotype_id':phenotype.id, 'phenotype_name':phenotype.phenotype_name, 'description':phenotype.phenotype_description, 'values':values_str, 'total_records': not_null_total})
    table = PhenotypeTable(phenotype_values)

    return render(request, 'search/dataview.html', {'table': table})

def showIndividuals(request):
    message = "The database currently contains <strong>" + str(Individual.objects.all().count()) + "</strong> individuals"
    message += " and <strong>" + str(IndividualIdentifier.objects.all().count()) + "</strong> individual IDs"
    message += "<br/>Individual IDs by source:"

    return render(request, 'search/summary.html', {'message': message})

def getIndividualData(request):
    source_counts = []
    for source in Source.objects.all():
        source_counts.append({'value': source.source_name, 'count': IndividualIdentifier.objects.filter(source_id=source.id).values('individual_id').distinct().count()})

    fieldnames = ['value','count']
    headers = dict( (n,n) for n in fieldnames )

    myFakeFile = io.StringIO()
    myWriter = csv.DictWriter( myFakeFile, fieldnames, delimiter='\t')
    myWriter.writerow(headers)
    for s in source_counts:
        myWriter.writerow(s)

    return HttpResponse(myFakeFile.getvalue(), content_type='text/tab-separated-values')

def showSamples(request):
    message = "The database currently contains <strong>" + str(Sample.objects.all().count()) + "</strong> samples"
    message += "<br/>Samples by study:"

    return render(request, 'search/summary.html', {'message': message})

def getSampleData(request):
    study_counts = []
    for study in Study.objects.all():
        study_counts.append({'value': study.study_name, 'count': StudySample.objects.filter(study_id=study.id).count()})

    fieldnames = ['value','count']
    headers = dict( (n,n) for n in fieldnames )

    myFakeFile = io.StringIO()
    myWriter = csv.DictWriter( myFakeFile, fieldnames, delimiter='\t')
    myWriter.writerow(headers)
    for s in study_counts:
        myWriter.writerow(s)

    return HttpResponse(myFakeFile.getvalue(), content_type='text/tab-separated-values')

def showPhenotypePlot(request, phenotype_id):
    phenotype = Phenotype.objects.get(id=phenotype_id)
    return render(request, 'search/barplot.html', {'id': phenotype_id, 'title': phenotype.phenotype_name})

def getPhenotypePlotData(request, phenotype_id):
    phenotype_value_counts = []
    phenotype = Phenotype.objects.get(id=phenotype_id)

    if phenotype.phenotype_type.phenotype_type == 'binary':
        values_dict_array = BinaryPhenotypeValue.objects.filter(phenotype_id=phenotype.id).order_by('phenotype_value').values('phenotype_value').distinct()
        for value_dict in values_dict_array:
            phenotype_value = str(value_dict['phenotype_value'])
            phenotype_value_count = BinaryPhenotypeValue.objects.filter(phenotype_id=phenotype.id, phenotype_value=phenotype_value).count()
            phenotype_value_counts.append({'value': phenotype_value, 'count': phenotype_value_count})

    elif phenotype.phenotype_type.phenotype_type == 'qualitative':
        values_dict_array = QualitativePhenotypeValue.objects.filter(phenotype_id=phenotype.id).values('phenotype_value').distinct()
        for value_dict in values_dict_array:
            phenotype_value = str(value_dict['phenotype_value'])
            phenotype_value_count = QualitativePhenotypeValue.objects.filter(phenotype_id=phenotype.id, phenotype_value=phenotype_value).count()
            phenotype_value_counts.append({'value': phenotype_value, 'count': phenotype_value_count})

    elif phenotype.phenotype_type.phenotype_type == 'quantitative':
        values_dict_array = QuantitiatvePhenotypeValue.objects.filter(phenotype_id=phenotype.id).order_by('phenotype_value').values('phenotype_value').distinct()
        for value_dict in values_dict_array:
            phenotype_value = str(value_dict['phenotype_value'])
            phenotype_value_count = QuantitiatvePhenotypeValue.objects.filter(phenotype_id=phenotype.id, phenotype_value=phenotype_value).count()
            phenotype_value_counts.append({'value': phenotype_value, 'count': phenotype_value_count})

    ## create a tsv file to pass to the d3 plotting library
    fieldnames = ['value','count']
    headers = dict( (n,n) for n in fieldnames )

    myFakeFile = io.StringIO()
    myWriter = csv.DictWriter( myFakeFile, fieldnames, delimiter='\t')
    myWriter.writerow(headers)
    for r in phenotype_value_counts:
        myWriter.writerow(r)

    print(myFakeFile.getvalue())

    return HttpResponse(myFakeFile.getvalue(), content_type='text/tab-separated-values')

def all_json_models(request, menuid):

    if menuid == 'phenotype':
        menuitems = Phenotype.objects.all()
    elif menuid == 'platform':
        menuitems = Platform.objects.all()
    elif menuid == 'study':
        menuitems = Study.objects.all()
    elif menuid == 'qc':
        menuitems = QC.objects.all()
    elif menuid == 'source':
        menuitems = Source.objects.all()

    json_models = serializers.serialize("json", menuitems)
    return HttpResponse(json_models, content_type="application/javascript")

def all_search_options(request, menuid, menuval):
    menuitems = []
    if menuid == 'phenotype':
        phenotype = Phenotype.objects.get(id=menuval)
        if phenotype.phenotype_type.phenotype_type == 'binary':
            menuitems = [{"value": "true", "text": "True" },{"value": "false", "text": "False"},{"value": "isnull", "text": "Is NULL"},{"value": "notnull", "text": "Is not NULL"}]
        elif phenotype.phenotype_type.phenotype_type == 'qualitative':

search/templates/search/barplot.html
{% extends "search/base.html" %}

{% block script %}
<style>
	.axis text {
		font: 10px sans-serif;
	}

	.axis path, .axis line {
		fill: none;
		stroke: #000;
		shape-rendering: crispEdges;
	}

	.bar {
		fill: steelblue;
		fill-opacity: .9;
	}

	.x.axis path {
		display: none;
	}
</style>
{% endblock %}

{% block content %}

<p class="lead" style="margin-top: 10px;margin-bottom: 10px">
	{{title}}
</p>

<script src="http://d3js.org/d3.v3.min.js"></script>
<script>

var margin = {top: 20, right: 20, bottom: 30, left: 40},
    width = 960 - margin.left - margin.right,
    height = 500 - margin.top - margin.bottom;

var x = d3.scale.ordinal()
    .rangeRoundBands([0, width], .1);

var y = d3.scale.linear()
    .range([height, 0]);

var xAxis = d3.svg.axis()
    .scale(x)
    .orient("bottom");

var yAxis = d3.svg.axis()
    .scale(y)
    .orient("left")

var svg = d3.select("#content").append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

d3.tsv("data", function(error, data) {

  data.forEach(function(d) {
    d.count = +d.count;
  });

  x.domain(data.map(function(d) { return d.value; }));
  y.domain([0, d3.max(data, function(d) { return d.count; })]);

  svg.append("g")
      .attr("class", "x axis")
      .attr("transform", "translate(0," + height + ")")
      .call(xAxis);

  svg.append("g")
      .attr("class", "y axis")
      .call(yAxis)
    .append("text")
      .attr("transform", "rotate(-90)")
      .attr("y", 6)
      .attr("dy", ".71em")
      .style("text-anchor", "end")

  svg.selectAll(".bar")
      .data(data)
    .enter().append("rect")
      .attr("class", "bar")
      .attr("x", function(d) { return x(d.value); })
      .attr("width", x.rangeBand())
      .attr("y", function(d) { return y(d.count); })
      .attr("height", function(d) { return height - y(d.count); });

});
</script>

{% endblock %}

search/templates/search/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>  
  <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}" />
  <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap-responsive.css" %}" />
  <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}" />
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}PhenoDB{% endblock %}</title>
  {% block script %}
  {% endblock %}
</head>

<body>
  <div class="navbar">
    <div class="navbar-inner">
      <a class="brand" href="/">PhenoDB</a>
    </div>
  </div>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span2">
        <div id="sidebar">
          <ul class="nav nav-list">
            <li class="nav-header">Menu</li>
            <li><a href="/"><i class="icon-home"></i>Home</a></li>
            <li><a href="/querybuilder"><i class="icon-search"></i>Query Builder</a></li>            
            <li><a href="/admin"><i class="icon-user"></i>Administration</a></li>
            <li class="nav-header">Data views</li>
            <li><a href="/individuals">Individuals</a></li>
            <li><a href="/sources">Sources</a></li>
            <li><a href="/phenotypes">Phenotypes</a></li>
            <li><a href="/collections">Collections</a></li>
            <li><a href="/samples">Samples</a></li>            
            <li><a href="/studies">Studies</a></li>
            <li><a href="/platforms">Platforms</a></li>
            <li><a href="/qcs">QCs</a></li>
            <li><a href="/missing">Missing Samples</a></li>
            <li class="nav-header">Reports</li>
            <li><a href="/duplicateSampleIDs">Duplicate Sample IDs</a></li>
          </ul> 
        </div>
      </div>
      <div class="span9">
        <div id="content">
          {% block content %}{% endblock %}
        </div>
      </div>
      <div class="span1">
      </div>
    </div>
  </div>
</body>
</html>

search/templates/search/dataview.html
{% extends "search/base.html" %}

{% block content %}	
    <p class="lead" style="margin-top: 10px;margin-bottom: 10px; color: red">
        {{warning|safe}}
    </p>
	{% load render_table from django_tables2 %}
	{% render_table table %}	
{% endblock %}

search/templates/search/duplicateSampleIDs.html
{% extends "search/base.html" %}

{% block content %} 
    <p class="lead warning">
        {{warning|safe}}
    </p>
    
    <table class="table duplicates">
    <thead>
        <tr>
            <th>PhenoDB ID</th>
            <th>Date Created</th>
            <th>Source:Identifiers</th>
            <th>Sample IDs</th>
        </tr>
    </thead>
        {% for v in duplicate_samples.values %}
            <tbody style="border: 2px solid #000000;">
            {% for individual in v %}
                <tr>
                    <td>{{individual.phenodbid}}</td>
                    <td>{{individual.date|date:"d/m/Y H:i:s"}}</td>
                    <td>
                        {% for source, identifiers in individual.individual_identifier_sources.items %}
                            <span class="sourcename">{{source}}</span>:&nbsp;{{identifiers}}<br>
                        {% endfor %}
                    </td>
                    <td>{{individual.sample_ids}}</td>
                </tr>
            {% endfor %}
            </tbody>
        {% endfor %}
    </table>
{% endblock %}

search/templates/search/home.html
{% extends "search/base.html" %}

{% block content %}
  <p class="lead">Welcome to PhenoDB.</p>
  <p>Please direct any bug reports, enhancement ideas or questions about PhenoDB to the GitHub <a href="https://github.com/wtsi-medical-genomics/phenodb/issues">Issue Tracker</a>.</p>
{% endblock %}

search/templates/search/idresults.html
{% extends "search/base.html" %}

{% block content %}
  {% load render_table from django_tables2 %}
  {% render_table table %}
{% endblock %}

search/templates/search/idsearch.html
{% extends "search/base.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Search" class="btn btn-large btn-primary"/>
  </form>
{% endblock %}

search/templates/search/queryresults.html
{% extends "search/base.html" %}

{% block script %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
  
  <script type="text/javascript">
    $(document).ready(function() {
 	  $("[id^=results_per_page]").change(function() { 				
 		var perpage = $(this).val() 				
 		if (perpage != 'message') {
		  var url = "";
		  if (perpage == 'all') {
		  	url = "/search/querybuilder" + '/1/{{page_results.paginator.count}}/';
		  } else {
		  	url = "/search/querybuilder" + '/{{page_results.number}}/' + perpage + '/';
		  }
		  window.location.href = url;
		} 								
	  });			
	});
  </script>
{% endblock %}

{% block content %}
  <p class="lead">Found {{count}} records matching your query:</p>
  
  <ul>
  {% for m in query_summary %}  	
    <p class="lead">{{ m }}
  {% endfor %}
  </ul>

<div align="right">
  <select name="results_per_page" id="results_per_page">
    <option value="message">Select Results Per Page</option>
    <option value="25">25</option>
    <option value="50">50</option>
    <option value="100">100</option>
    <option value="250">250</option>
    <option value="all">View all</option>            
  </select>
</div>
  
  {{tablehtml|safe}}

<div>
  <a href="{% url 'search:exportcsv' %}"><i class="icon-file"></i><em>export to .tsv</em></a>
</div>

<div class="pagination pagination-centered">
  <ul>
    {% if page_results.has_previous %}
      <li>
        <a href="{% url 'search:querypage' page=page_results.previous_page_number results_per_page=results_per_page %}">
          previous
        </a>
      </li>
    {% endif %}
    
    <li class="active">
      <a href="#">
        {{ page_results.number }} of {{ page_results.paginator.num_pages }}
      </a>
    </li>
    
    {% if page_results.has_next %}
      <li>
        <a href="{% url 'search:querypage' page=page_results.next_page_number results_per_page=results_per_page %}">
          next
        </a>
      </li>
    {% endif %}

  </ul>  
</div>

{% endblock %}

search/templates/search/summary.html
{% extends "search/base.html" %}

{% block script %}
<style>
	.axis text {
		font: 10px sans-serif;
	}

	.axis path, .axis line {
		fill: none;
		stroke: #000;
		shape-rendering: crispEdges;
	}

	.bar {
		fill: steelblue;
		fill-opacity: .9;
	}

	.x.axis text {
 		text-anchor: start !important;
	}

	.x.axis path {
		display: none;
    }

    .sort-values-checkbox {
        float: right;
    }

</style>

{% endblock %}

{% block content %}
<p class="lead" style="margin-top: 10px;margin-bottom: 10px">
	{{message|safe}}
</p>
<div class="sort-values-checkbox">
    <input type="checkbox"> Sort values
</div>
<script src="http://d3js.org/d3.v3.min.js"></script>
<script>
	var margin = {
		top : 20,
		right : 20,
		bottom : 200,
		left : 40
	}, width = 960 - margin.left - margin.right, height = 600 - margin.top - margin.bottom;

	var x = d3.scale.ordinal()
		.rangeRoundBands([0, width], .1, 1);

	var y = d3.scale.linear()
		.range([height, 0]);

	var xAxis = d3.svg.axis()
		.scale(x)
		.orient("bottom");

	var yAxis = d3.svg.axis()
		.scale(y)
		.orient("left");

	var svg = d3.select("#content").append("svg")
		.attr("width", width + margin.left + margin.right)
		.attr("height", height + margin.top + margin.bottom)
		.append("g")
			.attr("transform", "translate(" + margin.left + "," + margin.top + ")");

	d3.tsv("data", function(error, data) {

		data.forEach(function(d) {
			d.count = +d.count;
		});

		x.domain(data.map(function(d) {
			return d.value;
		}));
		y.domain([0, d3.max(data, function(d) {
			return d.count;
		})]);

		var axis = svg.append("g")
			.attr("class", "x axis")
			.attr("transform", "translate(0," + height + ")")
			.call(xAxis);
		
		axis.selectAll("text")
			.attr("transform", function(d) { return "rotate(50)translate(10, -5 )";});
		
		svg.append("g")
				.attr("class", "y axis")
				.call(yAxis)
			.append("text")
				.attr("transform", "rotate(-90)")
				.attr("y", 6)
				.attr("dy", ".71em")
				.style("text-anchor", "end")
				.text("count");

		svg.selectAll(".bar")
			.data(data)
		.enter().append("rect")
			.attr("class", "bar")
			.attr("x", function(d) { return x(d.value);	})
			.attr("width", x.rangeBand())
			.attr("y", function(d) { return y(d.count);	})
			.attr("height", function(d) { return height - y(d.count); });

		d3.select("input").on("change", change);

		var sortTimeout = setTimeout(function() {
			d3.select("input")
			.property("checked", true)
			.each(change);
		}, 1000);

		function change() {
			clearTimeout(sortTimeout);

			// Copy-on-write since tweens are evaluated after a delay.
			var x0 = x.domain(data.sort(this.checked
				? function(a, b) {return b.count - a.count;}
				: function(a, b) {return d3.ascending(a.value, b.value);})
			.map(function(d) {return d.value;})
			).copy();

			var transition = svg.transition().duration(750),
				 delay = function(d, i) { return i * 50; };

			transition.selectAll(".bar")
				.delay(delay)
				.attr("x", function(d) {
					return x0(d.value);
				});

			transition.select(".x.axis")
				.call(xAxis)
				.selectAll("g")
				.delay(delay);
		}

	});

</script>

{% endblock %}